# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X2b9O_kx_fFQ4h51Sen-mA3zg3Fd5X5K
"""

!pip install requests

import requests 
from pprint import pprint

params = {
    'latitude': '55.7577374',
    'longitude': '37.6164793',
    'query': 'Манты'
}

url = 'https://api.delivery-club.ru/api1.2/vendors/search'
#https://api.delivery-club.ru/api1.2/vendors/search?latitude=55.7577374&longitude=37.6164793&query=%D0%BC%D0%B0%D0%BD%D1%82%D1%8B&cacheBreaker=1664655282

response = requests.get(url=url, params=params)

print(response.status_code)

response.url

pprint(response.json())

vendors = response.json()['vendors']

pprint(vendors[0])

count = 0
for vendor in vendors:
  #print(vendor['name'], vendor['delivery']['price']['value'])
  if vendor['delivery']['price']['value'] == 0:
    count += 1
print(count)

count_all = int(len(vendors))

Free_delivery = count / count_all
print(Free_delivery)

NotFree_delivery = (count_all - count) / count_all

print(NotFree_delivery)

